"""Generate BRepCheck_WireClass2d.cxx from BRepTopAdaptor_FClass2d.cxx of OCCT 8.0.1 (defect 018, port to 8.0.1).

Defect 018. BRepCheck_Face::ClassifyWires may skip a classification only where it can prove the answer, and the
proof needs what BRepTopAdaptor_FClass2d keeps private (TabOrien, the polygon and tolerances it hands to
CSLib_Class2d). The copy is the original byte for byte except for two mechanical changes:
  1) the class name BRepTopAdaptor_FClass2d -> BRepCheck_WireClass2d (both classes live in TKTopAlgo);
  2) after each of the three lines
         TabClass.Append(CSLib_Class2d(<pts>, FlecheU, FlecheV, Umin, Vmin, Umax, Vmax));
     one line with the same arguments
         recordPolygon(<pts>, FlecheU, FlecheV, Umin, Vmin, Umax, Vmax); // defect 018
     which only stores copies of scalars derived from them (BRepCheck_WireClass2d.hxx).
The source must be the V8_0_1 file (it changed since 7.8.1: safeIncrement/isDegenerated of PR #733, CSLib_Class2d
held by value): md5 of its LF text is checked. The output is written with LF line ends.

    python gen_wireclass2d.py <OCCT 8.0.1 source root>        e.g.  python gen_wireclass2d.py C:/dev/occt-801-018
    python gen_wireclass2d.py <root> --check                   exit 1 if the file in the tree differs from the output
"""
import hashlib
import os
import re
import sys

SRC_MD5 = "0f602254b2572e1374d61bd048f640a2"  # V8_0_1 (b8f597c6) BRepTopAdaptor_FClass2d.cxx, LF
PKG = os.path.join("src", "ModelingAlgorithms", "TKTopAlgo")
APPEND = re.compile(r"^([ \t]*)TabClass\.Append\(CSLib_Class2d\((\w+), "
                    r"FlecheU, FlecheV, Umin, Vmin, Umax, Vmax\)\);\n", re.M)
BANNER = ("// Defect 018 (https://github.com/fozzfut/freecad-kernel-fixes). GENERATED by\n"
          "// issues/018-occt-brepcheck-face-quadratic-wires/build-scripts-801/gen_wireclass2d.py from\n"
          "// src/ModelingAlgorithms/TKTopAlgo/BRepTopAdaptor/BRepTopAdaptor_FClass2d.cxx of OCCT 8.0.1\n"
          "// (md5 %s): the class is renamed and a recordPolygon() line follows each CSLib_Class2d\n"
          "// construction. Do not edit this file; change the generator and run it again.\n" % SRC_MD5)


def generate(root):
    src = os.path.join(root, PKG, "BRepTopAdaptor", "BRepTopAdaptor_FClass2d.cxx")
    data = open(src, "rb").read().replace(b"\r\n", b"\n")
    got = hashlib.md5(data).hexdigest()
    if got != SRC_MD5:
        sys.exit("refusing: %s has md5 %s, not the V8_0_1 file %s" % (src, got, SRC_MD5))
    text = data.decode("ascii")
    count = [0]

    def add_record(m):
        count[0] += 1
        return m.group(0) + "%srecordPolygon(%s, FlecheU, FlecheV, Umin, Vmin, Umax, Vmax); // defect 018\n" % (
            m.group(1), m.group(2))

    text = APPEND.sub(add_record, text)
    if count[0] != 3:
        sys.exit("refusing: expected 3 CSLib_Class2d constructions, found %d" % count[0])
    text = text.replace("BRepTopAdaptor_FClass2d", "BRepCheck_WireClass2d")
    return (BANNER + text).encode("ascii")


if __name__ == "__main__":
    root = sys.argv[1]
    out = generate(root)
    dst = os.path.join(root, PKG, "BRepCheck", "BRepCheck_WireClass2d.cxx")
    if "--check" in sys.argv[2:]:
        cur = open(dst, "rb").read() if os.path.isfile(dst) else b""
        ok = cur == out
        print("%s: %s (md5 %s)" % (dst, "UP TO DATE" if ok else "DIFFERS", hashlib.md5(out).hexdigest()))
        sys.exit(0 if ok else 1)
    with open(dst, "wb") as f:
        f.write(out)
    print("wrote %s md5 %s" % (dst, hashlib.md5(out).hexdigest()))
