"""Build one whole OCCT 8.0.1 toolkit DLL as a drop-in for the FreeCAD weekly (kernel batch 1 lane).

usage: build_tk.py <TK> <occt-tree-root> <out-dir> [--define NAME[=VAL]]... [--toolset 14.36|<env.bat>]
Writes <out-dir>/build.bat and prints its path; run it through
  bash C:/dev/tools/buildlock.sh cmd //c <out-dir>/build.bat
Flags (kernel-src REPORT, LibPack 3.5.5): /EHa /GR C++17 /O2 /Ob2 /MD /fp:precise, exceptions ON, no /GL (no
LTCG), OCC_CONVERT_SIGNALS undefined, same HAVE_* defines as the kernel-src TKMesh probe. Links against import
libraries generated from the WEEKLY DLL exports (mkdef.py), so the result binds to the weekly's own dependencies.
Include path: every directory of <occt-tree-root>/src holding headers (the tree itself, so a patched header wins).
"""
import os
import re
import sys

WEEKLY_BIN = r"C:\dev\FreeCAD-occt8\FreeCAD_weekly-2026.09.23-Windows-x86_64-experimental\bin"
IMPLIB = r"C:\dev\occt8-mig\kb1\implib"
VCVARS = r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat"

args = sys.argv[1:]
tk, root, out = args[0], os.path.abspath(args[1]), os.path.abspath(args[2])
defines, toolset, preinc, override = [], "14.36", [], {}
i = 3
while i < len(args):
    if args[i] == "--define":
        defines.append(args[i + 1]); i += 2
    elif args[i] == "--preinc":  # extra include dir searched BEFORE the tree (mutant headers)
        preinc.append(os.path.abspath(args[i + 1])); i += 2
    elif args[i] == "--override":  # <basename.cxx>=<replacement path>: compile this file instead (mutants)
        k, v = args[i + 1].split("=", 1); override[k] = os.path.abspath(v); i += 2
    elif args[i] == "--toolset":
        toolset = args[i + 1]; i += 2
    else:
        sys.exit("bad arg " + args[i])

src = os.path.join(root, "src")
tkdir = None
for mod in os.listdir(src):
    cand = os.path.join(src, mod, tk)
    if os.path.isdir(cand) and os.path.isfile(os.path.join(cand, "PACKAGES.cmake")):
        tkdir = cand
if not tkdir:
    sys.exit("toolkit not found: " + tk)


def cmake_list(path, var_suffix):
    txt = open(path, encoding="utf-8").read()
    # k027: drop CMake comments first (8.0.1 FILES.cmake comments contain ')' that ended the list early)
    txt = "\n".join(l.split("#", 1)[0] for l in txt.splitlines())
    m = re.search(r"set\s*\(\s*\S*%s\s+(.*?)\)" % var_suffix, txt, re.S)
    return [w for w in m.group(1).split() if not w.startswith("#")] if m else []


pkgs = cmake_list(os.path.join(tkdir, "PACKAGES.cmake"), "LIST_OF_PACKAGES")
deps = [d for d in cmake_list(os.path.join(tkdir, "EXTERNLIB.cmake"), "EXTERNAL_LIBS") if d.startswith("TK")]
srcs = []
for p in pkgs:
    for f in cmake_list(os.path.join(tkdir, p, "FILES.cmake"), "FILES"):
        if f.endswith((".cxx", ".cpp", ".c")):
            srcs.append(override.pop(f) if f in override else os.path.join(tkdir, p, f))
if override:
    sys.exit("override not used: %s" % override)
incs = []
for dp, dn, fn in os.walk(src):
    dn[:] = sorted(d for d in dn if d != "GTests")
    if any(f.endswith((".hxx", ".lxx", ".gxx", ".pxx", ".h")) for f in fn):
        incs.append(dp)
os.makedirs(os.path.join(out, "obj"), exist_ok=True)
with open(os.path.join(out, "inc.rsp"), "w") as f:
    f.write("\n".join('/I"%s"' % d.replace("\\", "/") for d in preinc + incs) + "\n")
with open(os.path.join(out, "srcs.rsp"), "w") as f:
    f.write("\n".join('"%s"' % s for s in srcs) + "\n")
if os.path.isfile(toolset):
    env = 'call "%s" >nul' % toolset
else:
    env = 'call "%s" x64 -vcvars_ver=%s >nul' % (VCVARS, toolset)
dflags = " ".join("/D%s" % d for d in defines)
libs = " ".join(r"%s\%s.lib" % (IMPLIB, d) for d in deps)
bat = r"""@echo off
rem generated by build_tk.py: {tk} from {root}
{env}
cd /d "{out}"
cl 2>&1 | findstr "19." > toolset.txt
set MP=/MP4
if "%BUILDLOCK_LOWMEM%"=="1" set MP=/MP2
echo MP=%MP% > mp.txt
for %%T in ({deplist}) do (
  if not exist "{implib}\%%T.lib" (
    python C:\dev\occt8-mig\kb1\tools\mkdef.py "{wbin}\%%T.dll" "{implib}\%%T.def" > nul || (echo MKDEF-FAIL %%T & exit /b 1)
    lib /nologo /machine:x64 /def:"{implib}\%%T.def" /out:"{implib}\%%T.lib" > nul || (echo LIB-FAIL %%T & exit /b 1)
  )
)
cl /c /nologo %MP% /EHa /GR /std:c++17 /O2 /Ob2 /DNDEBUG /MD /fp:precise /W4 /wd26812 /wd4996 /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /D_WIN32_WINNT=0x0601 /DHAVE_FREETYPE /DHAVE_VTK /DHAVE_RAPIDJSON /DHAVE_EIGEN {dflags} /bigobj @inc.rsp /Foobj\ @srcs.rsp > cl.log 2>&1
echo CL-EXIT=%ERRORLEVEL%
if not "%ERRORLEVEL%"=="0" exit /b 1
rc /nologo /I"{stdinc}" /fo {tk}.res {tk}.rc > rc.log 2>&1
echo RC-EXIT=%ERRORLEVEL%
if not "%ERRORLEVEL%"=="0" exit /b 1
link /nologo /DLL /MACHINE:X64 /OUT:{tk}.dll /IMPLIB:{tk}.lib obj\*.obj {tk}.res {libs} > link.log 2>&1
echo LINK-EXIT=%ERRORLEVEL%
if not "%ERRORLEVEL%"=="0" exit /b 1
echo BUILD-OK {tk}
""".format(tk=tk, root=root, env=env, out=out, deplist=" ".join(deps), implib=IMPLIB, wbin=WEEKLY_BIN,
           dflags=dflags, libs=libs, stdinc=r"C:\dev\occt8-mig\kb1\gen")  # k027: fixed path (copy of kb1/tools/build_tk.py)
# version resource exactly as OCCT's CMake makes it (adm/templates/occt_toolkit.rc.in, PROJECT_NAME = toolkit)
rc_in = open(os.path.join(root, "adm", "templates", "occt_toolkit.rc.in"), encoding="utf-8").read()
with open(os.path.join(out, tk + ".rc"), "w", encoding="utf-8") as f:
    f.write(rc_in.replace("@PROJECT_NAME@", tk))
with open(os.path.join(out, "build.bat"), "w") as f:
    f.write(bat)
print("%s: %d packages, %d sources, deps %s, %d include dirs -> %s" % (
    tk, len(pkgs), len(srcs), ",".join(deps), len(incs), os.path.join(out, "build.bat")))
