@echo off
rem generated by build_tk.py: TKOffset from C:\dev\occt-801-034loc
call "C:\dev\toolchains\msvc-14.50\vcvars150.bat" >nul
cd /d "C:\dev\occt8-mig\offset-034loc\rv1\d0"
cl 2>&1 | findstr "19." > toolset.txt
set MP=/MP2
if "%BUILDLOCK_LOWMEM%"=="1" set MP=/MP2
echo MP=%MP% > mp.txt
for %%T in (TKFillet TKBRep TKTopAlgo TKMath TKernel TKGeomBase TKG2d TKG3d TKGeomAlgo TKShHealing TKBO TKPrim TKBool) do (
  if not exist "C:\dev\occt8-mig\kb1\implib\%%T.lib" (
    python C:\dev\occt8-mig\kb1\tools\mkdef.py "C:\dev\FreeCAD-occt8\FreeCAD_weekly-2026.09.23-Windows-x86_64-experimental\bin\%%T.dll" "C:\dev\occt8-mig\kb1\implib\%%T.def" > nul || (echo MKDEF-FAIL %%T & exit /b 1)
    lib /nologo /machine:x64 /def:"C:\dev\occt8-mig\kb1\implib\%%T.def" /out:"C:\dev\occt8-mig\kb1\implib\%%T.lib" > nul || (echo LIB-FAIL %%T & exit /b 1)
  )
)
cl /c /nologo %MP% /EHa /GR /std:c++17 /O2 /Ob2 /DNDEBUG /MD /fp:precise /W4 /wd26812 /wd4996 /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE /D_WIN32_WINNT=0x0601 /DHAVE_FREETYPE /DHAVE_VTK /DHAVE_RAPIDJSON /DHAVE_EIGEN  /bigobj @inc.rsp /Foobj\ @srcs.rsp > cl.log 2>&1
echo CL-EXIT=%ERRORLEVEL%
if not "%ERRORLEVEL%"=="0" exit /b 1
rc /nologo /I"C:\dev\occt8-mig\kb1\gen" /fo TKOffset.res TKOffset.rc > rc.log 2>&1
echo RC-EXIT=%ERRORLEVEL%
if not "%ERRORLEVEL%"=="0" exit /b 1
link /nologo /DLL /MACHINE:X64 /OUT:TKOffset.dll /IMPLIB:TKOffset.lib obj\*.obj TKOffset.res C:\dev\occt8-mig\kb1\implib\TKFillet.lib C:\dev\occt8-mig\kb1\implib\TKBRep.lib C:\dev\occt8-mig\kb1\implib\TKTopAlgo.lib C:\dev\occt8-mig\kb1\implib\TKMath.lib C:\dev\occt8-mig\kb1\implib\TKernel.lib C:\dev\occt8-mig\kb1\implib\TKGeomBase.lib C:\dev\occt8-mig\kb1\implib\TKG2d.lib C:\dev\occt8-mig\kb1\implib\TKG3d.lib C:\dev\occt8-mig\kb1\implib\TKGeomAlgo.lib C:\dev\occt8-mig\kb1\implib\TKShHealing.lib C:\dev\occt8-mig\kb1\implib\TKBO.lib C:\dev\occt8-mig\kb1\implib\TKPrim.lib C:\dev\occt8-mig\kb1\implib\TKBool.lib > link.log 2>&1
echo LINK-EXIT=%ERRORLEVEL%
if not "%ERRORLEVEL%"=="0" exit /b 1
echo BUILD-OK TKOffset
